[build]
  command = "npm run build"
  publish = "dist"        

[[redirects]]
  from = "/hf-api/*"
  to = "https://router.huggingface.co/:splat"
  status = 200
  force = true
  headers = {Authorization = "Bearer $VITE_HUGGINGFACE_API_KEY"}